repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-builtin-literals
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-illegal-windows-names
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-shebang-scripts-are-executable
    -   id: check-symlinks
    -   id: check-toml
    -   id: check-vcs-permalinks
    -   id: check-xml
        # Full check against all YAML files excluding mkdocs.yml
    -   id: check-yaml
    -   id: debug-statements
    -   id: destroyed-symlinks
    -   id: detect-aws-credentials
        args: [ --allow-missing-credentials ]
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: fix-byte-order-marker
    -   id: forbid-submodules
    -   id: forbid-new-submodules
    -   id: mixed-line-ending
    -   id: no-commit-to-branch
    -   id: pretty-format-json
        exclude: ^docusaurus\/package-lock.json$
        args: [ --autofix ]
    -   id: trailing-whitespace

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.10
    hooks:
    - id: ruff-check
      args: [ --fix, --exit-non-zero-on-fix ]
    - id: ruff-format

- repo: https://github.com/gitleaks/gitleaks
  rev: v8.27.2
  hooks:
    - id: gitleaks

-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']

-   repo: local
    hooks:
    -   id: check-license-header
        name: check license header
        pass_filenames: false
        language: system
        entry: npm
        args: [
            'exec', '--',
            'github:viperproject/check-license-header#v1', 'check', '--config', './.github/workflows/check-license-header.json']
    -   id: pyright
        name: pyright
        pass_filenames: true
        language: system
        entry: bash -c 'for x in "$@"; do (cd `dirname $x`; pwd; uv run --frozen --all-extras --dev pyright --stats;); done;' --
        stages: [pre-push]
        files: (src|samples)\/.*\/pyproject.toml
    -   id: pytest
        name: pytest
        pass_filenames: true
        language: system
        entry: bash -c 'for x in "$@"; do (cd `dirname $x`; pwd; uv run --frozen pytest --cov --cov-branch --cov-report=term-missing;); done;' --
        stages: [pre-push]
        files: src\/.*\/pyproject.toml
