name: 'Dependency Review'
on: [pull_request]

permissions: {}

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5.0.0
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@3c4e3dcb1aa7874d2c16be7d79418e9b7efd6261 #v4.8.2
        with:
          # https://github.com/actions/dependency-review-action/issues/944
          allow-dependencies-licenses: 'pkg:pypi/uv@0.8.10'
          deny-licenses: |
            AGPL-1.0,AGPL-1.0-only,AGPL-1.0-or-later,AGPL-3.0,AGPL-3.0-only,AGPL-3.0-or-later,
            AML,
            CDLA-Sharing-1.0,
            CPAL-1.0,
            MIT-enna,
            EUPL-1.1,EUPL-1.2,
            LGPL-3.0+,LGPL-3.0,LGPL-3.0-only,LGPL-3.0-or-later,
            GPL-3.0-only,GPL-3.0-or-later,GPL-3.0,GPL-3.0+,GPL-3.0-with-autoconf-exception,GPL-3.0-with-GCC-exception,
            NASA-1.3,
            ODbL-1.0,
            OSL-3.0,
            Parity-7.0.0,
            RPSL-1.0,
            SSPL-1.0
          ## Honest Public License (HPL) 1.0
